### ISSUE TITLE
example fails unless Rcpp is loaded

### ISSUE THREAD

**Issue by adalardo** [Lobz/facilitation#1]
If Rcpp is not loaded the message error is shown: "...function 'enterRNGScope' not provided by package 'Rcpp'" . I believe the solution is include:
"import(Rcpp)"
to NAMESPACE file and

"Imports: Rcpp"
to DESCRIPTION

**Comment by andrechalom** [comment]
I am having the same problem in a different package (and unable to test it
at the moment), please let me know if you fix it.

If I read correctly, it is necessary to have Rcpp on both the "Imports" and
"LinkingTo" fields of the DESCRIPTION?

**Comment by adalardo** [comment]
See the same issue in:

https://github.com/hadley/lineprof/issues/18

2015-11-11 14:41 GMT-02:00 andrechalom <notifications@github.com>:

> I am having the same problem in a different package (and unable to test it
> at the moment), please let me know if you fix it.
>
> If I read correctly, it is necessary to have Rcpp on both the "Imports" and
> "LinkingTo" fields of the DESCRIPTION?
> On Nov 11, 2015 1:39 PM, "Alexandre Adalardo" <notifications@github.com>
> wrote:
>
> > If Rcpp is not loaded the message error is shown: "...function
> > 'enterRNGScope' not provided by package 'Rcpp'" . I believe the solution
> is
> > include:
> > "import(Rcpp)"
> > to NAMESPACE file and
> >
> > "Imports: Rcpp"
> > to DESCRIPTION
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Lobz/facilitation/issues/1>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lobz/facilitation/issues/1#issuecomment-155838777>.
>



-- 
Alexandre Adalardo de Oliveira
Professor Doutor
Universidade de São Paulo
IB-Depto Ecologia
http://labtrop.ib.usp.br <http://ecologia.ib.usp.br/labtrop>
adalardo@usp.br
____________________
aleadalardo@gmail.com
http://scholar.google.com.br/citations?user=O1gcrwIAAAAJ&hl=pt-BR

**Comment by adalardo** [comment]
Hi Chalom, 

It is confirmed. The problem was solved with the inclusion of 
"import(Rcpp)" to NAMESPACE file. We already have "import: Rcpp" in DESCRIPTION file. We need both!

**Comment by andrechalom** [comment]
Thanks a lot!

**Comment by Lobz** [comment]
Made the change, could you test again? R CMD check seems to work

**Comment by loverend** [comment]
Hi All, 

I have been trying to install the R version of ILISI  and am also getting this error. 
Please could someone explain how to correct this? How can I edit the name space?

 lisi_res <- lisi::compute_lisi(lisi::X, lisi::meta_data, c('label1', 'label2'))
Error in compute_simpson_index(t(dknn$nn.dists), t(dknn$nn.idx) - 1, labels,  : 
  function 'enterRNGScope' not provided by package 'Rcpp'

Thanks!
