### ISSUE TITLE
weird pattern with high dispersion: a regular slice of the area remains empty

### ISSUE THREAD

**Issue by Lobz** [Lobz/facilitation#18]
Notice in the image below how the righmost part of the plot is just empty.

![disperse5](https://cloud.githubusercontent.com/assets/1750256/15342469/cb717c40-1c6b-11e6-892e-f5261872173c.gif)

It could be nothing but it also could be something. This is not the first time I have encountered this pattern, always with very high dispersion (10-12 in a square of 40). Maybe something is wrong with the boundary condition?

edit: i had uploaded the wrong gif

**Comment by andrechalom** [comment]
Definetely sounds like boundary condition. But the x plot label shows 0-47 while the y is 0-40, is this intended?

**Comment by Lobz** [comment]
Yo're right. The map actually ends on 40. The problem must be in the definition of the x-axis in function spatialplot().

**Comment by Lobz** [comment]
No wait. Look closely, there's one single blue dot that appears on the rightmost boundary of the plot. Definetly a boundary condition error, since it should be impossible for a seed to be there.
