### ISSUE TITLE
individual id's carry on through several instantiations (optimized_output)

### ISSUE THREAD

**Issue by Lobz** [Lobz/facilitation#25]
if you call facByRates several times in a row, each time the minimun individual id is gonna be 1+the maximum from last time. This doesn't cause any trouble, but I find it a little disturbing. Why does this happen?

**Comment by andrechalom** [comment]
That's because the "next" ID is controlled by the `static unsigned long id_MAX` variable, which is persistent across simulations (as are all global and "globalish" variables, as far as I understand Rcpp). You can implement something on the Arena constructor that sets this id_MAX to zero.

**Comment by andrechalom** [comment]
Reopening the issue as this is relevant for `proceed`.
