### ISSUE TITLE
Rename functions

### ISSUE THREAD

**Issue by andrechalom** [Lobz/facilitation#31]
- run_test and test_parameters should be renamed to "run_sim" and "simulation"?
- facByRates could be renamed to "facilitation"
- fitted and fitted.rates should be renamed to avoid clash with R base function fitted

**Comment by Lobz** [comment]
changed fitted.rate-->mpm.fitted.rate
I don't think there is a function called fitted though?

**Comment by andrechalom** [comment]
Yes, the warning about "fitted" was actually caused by the "fitted.rate". But did you push these changes? Branch master on R/explore.R shows "fitted.rate" still.

**Comment by Lobz** [comment]
merged
