### ISSUE TITLE
begintime and endtime

### ISSUE THREAD

**Issue by andrechalom** [Lobz/facilitation#33]
Some functions are accessing objects "begintime" and "endtime" which seem to be global vars. This should be at least documented

**Comment by Lobz** [comment]
Can you pls specify which functions? I don't know what you're talking about.

**Comment by andrechalom** [comment]
Functions abundance_matrix, snapshotdataframe and spatialplot all define internally the following lapply:

```r
lapply(times,function(t){subset(data$data,begintime <= t & (endtime >= t | is.na(endtime)))})
```

However, I can't figure out where are begintime and endtime defined. Are they global variables? Are they being generated by Rcpp? If they are, they should be slots of the facilitation object, instead of global vars.

**Comment by Lobz** [comment]
They are **column names** of the data dataframe, which is part of the object returned by facilitation() (the data dataframe is the return of simulation())

Trying to figure out where to document that...
